### ISSUE TITLE
Add z-index to auto-list

### ISSUE THREAD

**Issue by PeterKnight** [abrimo/TinyMCE-Autocomplete-Plugin#1]
So happy to have found this script, thank you for putting this on github! I placed this inside a WordPress editor and noticed that in Full Screen mode (a WP feature) the auto list doesn't display without an appropriate z-index value. For people integrating this into WordPress, you might want to set the z-index to something like z-index: 1000000; for full screen mode support.

**Comment by abrimo** [comment]
That's great, I'm glad you found it useful and thanks for reporting the issue with Wordpress.
